In [1]:
import pandas as pd

In [2]:
titanic_dataset_github_url = "https://raw.githubusercontent.com/datasciencedojo/datasets/refs/heads/master/titanic.csv"

df = pd.read_csv(titanic_dataset_github_url)

In [3]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [4]:
Name = list[df['Name'].str.find("Sir")]
Name

list[0     -1
1     -1
2     -1
3     -1
4     -1
      ..
886   -1
887   -1
888   -1
889   -1
890   -1
Name: Name, Length: 891, dtype: int64]

In [5]:
df['Name'].str.replace("Mr.","Sir",regex=False).head()

0                              Braund, Sir Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                               Heikkinen, Miss. Laina
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                             Allen, Sir William Henry
Name: Name, dtype: str

In [6]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='str')

In [7]:
df.iloc[1:30]["Name"]

1     Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                Heikkinen, Miss. Laina
3          Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                              Allen, Mr. William Henry
5                                      Moran, Mr. James
6                               McCarthy, Mr. Timothy J
7                        Palsson, Master. Gosta Leonard
8     Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)
9                   Nasser, Mrs. Nicholas (Adele Achem)
10                      Sandstrom, Miss. Marguerite Rut
11                             Bonnell, Miss. Elizabeth
12                       Saundercock, Mr. William Henry
13                          Andersson, Mr. Anders Johan
14                 Vestrom, Miss. Hulda Amanda Adolfina
15                     Hewlett, Mrs. (Mary D Kingcome)
16                                 Rice, Master. Eugene
17                         Williams, Mr. Charles Eugene
18    Vander Planke, Mrs. Julius (Emelia Maria Vande...
19                              Masselmani, Mrs. Fatima
20                                 Fynney, Mr. Joseph J
21                                Beesley, Mr. Lawrence
22                          McGowan, Miss. Anna "Annie"
23                         Sloper, Mr. William Thompson
24                        Palsson, Miss. Torborg Danira
25    Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...
26                              Emir, Mr. Farred Chehab
27                       Fortune, Mr. Charles Alexander
28                        O'Dwyer, Miss. Ellen "Nellie"
29                                  Todoroff, Mr. Lalio
Name: Name, dtype: str

In [8]:
end = df.loc[1, 'Name'].find(")")

In [9]:
start = df.loc[1, 'Name'].find("(")

In [10]:
def name_substring(name):
    start = name.find("(")
    end = name.find(")")
    new_name = name[0:start]+name[end+1:]
    new_name = new_name.strip()
    return new_name

In [11]:
df["Trimed_name"] = df["Name"].apply(name_substring)

In [12]:
df["Trimed_name"]

0          Braund, Mr. Owen HarriBraund, Mr. Owen Harris
1                             Cumings, Mrs. John Bradley
2            Heikkinen, Miss. LainHeikkinen, Miss. Laina
3                           Futrelle, Mrs. Jacques Heath
4        Allen, Mr. William HenrAllen, Mr. William Henry
                             ...
886            Montvila, Rev. JuozaMontvila, Rev. Juozas
887    Graham, Miss. Margaret EditGraham, Miss. Marga...
888    Johnston, Miss. Catherine Helen "CarrieJohnsto...
889            Behr, Mr. Karl HowelBehr, Mr. Karl Howell
890                Dooley, Mr. PatricDooley, Mr. Patrick
Name: Trimed_name, Length: 891, dtype: str

In [13]:
data = {
    'Name': [
        'John Doe', 'Jane Smith', 'Emily Johnson',
        'Robert Brown', 'Anna-Marie Lee'
    ],
    'Email': [
        'john@example.com', 'jane.smith@work.org',
        'emily_j@data.net', 'robertb@yahoo.com',
        'anna.lee@company.co'
    ]
}

df = pd.DataFrame(data)

In [14]:
df.head()

             Name                Email
0        John Doe     john@example.com
1      Jane Smith  jane.smith@work.org
2   Emily Johnson     emily_j@data.net
3    Robert Brown    robertb@yahoo.com
4  Anna-Marie Lee  anna.lee@company.co

In [15]:
df["Name"].str.pad(width=20,side="right",fillchar='*')

0    John Doe************
1    Jane Smith**********
2    Emily Johnson*******
3    Robert Brown********
4    Anna-Marie Lee******
Name: Name, dtype: str

In [16]:
df = pd.read_csv("titanic.csv")

In [18]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [23]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

In [26]:
df["Embarked"].unique()

<StringArray>
['S', 'C', 'Q', 'N']
Length: 4, dtype: str

In [25]:
df["Embarked"]=df["Embarked"].fillna("N")

In [27]:
df['Embarked_cat_auto'] = df['Embarked'].astype('category')

In [28]:
df['Embarked_cat_auto'].unique()

['S', 'C', 'Q', 'N']
Categories (4, str): ['C', 'N', 'Q', 'S']

In [31]:
df['Embarked_cat_auto'].cat.categories

Index(['C', 'N', 'Q', 'S'], dtype='str')

In [32]:
df['Embarked_cust_cat']= pd.Categorical(
    df['Embarked'],
    categories=['N', 'S', 'C', 'Q'], # Custom order lower to higher (Ascending)
    ordered=True
)

In [33]:
df['Embarked_cust_cat'].cat.codes.unique()

array([1, 2, 3, 0], dtype=int8)

In [ ]:
df["Sex"] = df["Sex"].apply(lambda sex: 1 if "Sex"=="male" else 0)
df["Sex"]=df["Sex"]